# Generated by Django 3.2.13 on 2022-11-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_feature_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feature_image',
            new_name='featured_image',
        ),
    ]
